import { palmistryDisclaimers } from "../knowledge/disclaimers";
import type { PalmPattern } from "./types";

export const palmPatterns: PalmPattern[] = [
  {
    id: "long-life-clear-head",
    name: "长期投入型节奏",
    level: "strong",
    description: "生命线偏长且智慧线可观察时，适合归纳为稳定投入、长期打磨的娱乐画像。",
    lines: ["life-line", "head-line"],
    conditions: { required: ["lifeLine:long", "headLine:not_unclear"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.lifeLine === "long" && f.headLine !== "unclear",
    effects: {
      scores: { personality: 8, energy: 8 },
      keywords: ["长期主义"],
      achievements: [
        { name: "长期主义者", description: "倾向于把精力投向长期目标和稳定积累。" },
      ],
      discoveries: [
        {
          title: "长期投入型节奏",
          description: "生命线与智慧线组合显示出偏稳定、愿意持续打磨的娱乐化画像。",
          knowledgeNote: "传统掌纹体系常把生命线看作精力节奏，把智慧线看作思考方式。",
        },
      ],
    },
  },
  {
    id: "medium-life-stable",
    name: "稳态恢复",
    level: "supportive",
    description: "生命线中等清晰时，规则更偏向稳定节奏与可持续恢复。",
    lines: ["life-line"],
    conditions: { required: ["lifeLine:medium"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.lifeLine === "medium",
    effects: {
      scores: { energy: 5 },
      keywords: ["稳态恢复"],
      achievements: [
        { name: "稳态经营者", description: "更适合用稳定节奏推进目标，而不是短期冲刺。" },
      ],
    },
  },
  {
    id: "unclear-life",
    name: "生命线观察受限",
    level: "caution",
    description: "生命线不清晰时，优先给出重拍建议，不做身体或寿命判断。",
    lines: ["life-line"],
    conditions: { required: ["lifeLine:unclear"], caution: ["photo_visibility"] },
    source: "rule-engine",
    safetyNote: "图片质量会影响掌纹可见度，不能据此做身体判断。",
    when: (f) => f.lifeLine === "unclear",
    effects: {
      scores: { energy: -4 },
      advice: ["如果想看生命线，请让掌心占画面 80%，避免反光。"],
      discoveries: [
        {
          title: "生命线观察受限",
          description: "这不代表状态不好，只说明照片条件不适合稳定观察。",
          knowledgeNote: "图片质量会影响掌纹可见度，不能据此做身体判断。",
        },
      ],
    },
  },
  {
    id: "straight-head",
    name: "理性拆解型",
    level: "strong",
    description: "智慧线偏直时，传统娱乐解读常归纳为重视逻辑、事实和效率。",
    lines: ["head-line"],
    conditions: { required: ["headLine:straight"] },
    source: "rule-engine",
    safetyNote: "这是传统说法的现代归纳，不等于真实人格测评。",
    when: (f) => f.headLine === "straight",
    effects: {
      scores: { personality: 7, career: 5 },
      keywords: ["清晰决策"],
      achievements: [
        { name: "理性拆解者", description: "倾向于先拆问题、再做选择。" },
      ],
      discoveries: [
        {
          title: "理性路线明显",
          description: "智慧线偏直时，娱乐解读中常归纳为重视逻辑、事实和效率。",
          knowledgeNote: "这是传统说法的现代归纳，不等于真实人格测评。",
        },
      ],
    },
  },
  {
    id: "curved-head",
    name: "创意感知型",
    level: "strong",
    description: "智慧线偏弯时，娱乐角度常与想象力、创意和感性思维联系。",
    lines: ["head-line"],
    conditions: { required: ["headLine:curved"] },
    source: "rule-engine",
    safetyNote: "只作为自我观察入口，不是能力评估。",
    when: (f) => f.headLine === "curved",
    effects: {
      scores: { personality: 6, career: 4 },
      keywords: ["创意感知"],
      achievements: [
        { name: "创意探索者", description: "更容易从感受、联想和灵感中找到方案。" },
      ],
      discoveries: [
        {
          title: "想象力线索",
          description: "智慧线偏弯时，娱乐角度常与想象力、创意和感性思维联系。",
          knowledgeNote: "只作为自我观察入口，不是能力评估。",
        },
      ],
    },
  },
  {
    id: "unclear-head",
    name: "智慧线观察受限",
    level: "caution",
    description: "智慧线不清晰时，不把照片噪声解释成思维结论。",
    lines: ["head-line"],
    conditions: { required: ["headLine:unclear"], caution: ["photo_visibility"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.headLine === "unclear",
    effects: {
      scores: { personality: -3 },
      advice: ["智慧线不清晰时，不要急着解读，优先重拍清晰照片。"],
    },
  },
  {
    id: "deep-heart",
    name: "真诚表达型",
    level: "strong",
    description: "感情线较明显时，传统娱乐解读常联想到情绪投入和表达需求。",
    lines: ["heart-line"],
    conditions: { required: ["heartLine:deep"] },
    source: "rule-engine",
    safetyNote: "不用于判断关系结果或婚恋走向。",
    when: (f) => f.heartLine === "deep",
    effects: {
      scores: { relationship: 8 },
      keywords: ["真诚表达"],
      achievements: [
        { name: "情感观察家", description: "对关系氛围和情绪变化可能比较敏感。" },
      ],
      discoveries: [
        {
          title: "情绪表达较有存在感",
          description: "感情线较明显时，传统娱乐解读常联想到情绪投入和表达需求。",
          knowledgeNote: "不用于判断关系结果或婚恋走向。",
        },
      ],
    },
  },
  {
    id: "light-heart",
    name: "温和边界型",
    level: "supportive",
    description: "感情线偏浅时，娱乐化表达偏向温和表达与边界练习。",
    lines: ["heart-line"],
    conditions: { required: ["heartLine:light"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.heartLine === "light",
    effects: {
      scores: { relationship: 3 },
      keywords: ["温和边界"],
      advice: ["表达感受时可以更具体一点，减少让别人猜。"],
    },
  },
  {
    id: "forked-heart",
    name: "关系边界思考者",
    level: "balanced",
    description: "感情线分叉在传统说法中常被娱乐化理解为情感细腻、会思考关系边界。",
    lines: ["heart-line"],
    conditions: { required: ["heartLine:forked"] },
    source: "rule-engine",
    safetyNote: "不代表一定会发生任何关系事件。",
    when: (f) => f.heartLine === "forked",
    effects: {
      scores: { relationship: 6 },
      keywords: ["关系边界"],
      achievements: [
        { name: "关系思考者", description: "容易在感受和边界之间寻找平衡。" },
      ],
      discoveries: [
        {
          title: "情感细腻线索",
          description: "感情线分叉在传统说法中常被娱乐化理解为情感细腻、会思考关系边界。",
          knowledgeNote: "不代表一定会发生任何关系事件。",
        },
      ],
    },
  },
  {
    id: "strong-fate",
    name: "目标感路径",
    level: "strong",
    description: "事业线较明显时，娱乐解读中常与责任感、路径感和阶段目标联系。",
    lines: ["fate-line"],
    conditions: { required: ["fateLine:strong"] },
    source: "rule-engine",
    safetyNote: "不用于预测事业成败。",
    when: (f) => f.fateLine === "strong",
    effects: {
      scores: { career: 10 },
      keywords: ["目标感"],
      achievements: [
        { name: "行动力玩家", description: "目标一旦明确，就更容易进入推进状态。" },
      ],
      discoveries: [
        {
          title: "事业驱动力较强",
          description: "事业线较明显时，娱乐解读中常与责任感、路径感和阶段目标联系。",
          knowledgeNote: "不用于预测事业成败。",
        },
      ],
    },
  },
  {
    id: "weak-fate",
    name: "目标拆解提示",
    level: "supportive",
    description: "事业线偏弱时，报告只给目标拆解建议，不做职业预测。",
    lines: ["fate-line"],
    conditions: { required: ["fateLine:weak"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.fateLine === "weak",
    effects: {
      scores: { career: 3 },
      advice: ["事业线偏弱时，可把注意力放在目标拆解，而不是等待方向突然清晰。"],
    },
  },
  {
    id: "absent-fate",
    name: "方向感自建",
    level: "caution",
    description: "事业线不明显并不代表职业不好，更适合用计划表建立方向感。",
    lines: ["fate-line"],
    conditions: { required: ["fateLine:absent"] },
    source: "rule-engine",
    safetyNote: "不用于预测事业成败。",
    when: (f) => f.fateLine === "absent",
    effects: {
      scores: { career: -2 },
      advice: ["事业线不明显并不代表职业不好，更适合用计划表建立方向感。"],
    },
  },
  {
    id: "strong-fate-visible-sun",
    name: "作品型表达驱动",
    level: "strong",
    description: "事业线与太阳线同时可见时，娱乐角度可理解为表达欲和目标感同框。",
    lines: ["fate-line", "sun-line"],
    conditions: { required: ["fateLine:strong", "sunLine:visible"] },
    source: "rule-engine",
    safetyNote: "不代表名气或收入，只是文化象征。",
    when: (f) => f.fateLine === "strong" && f.sunLine === "visible",
    effects: {
      scores: { career: 6, wealth: 5 },
      keywords: ["表达驱动"],
      achievements: [
        { name: "作品型选手", description: "适合把能力沉淀成作品、案例或可见成果。" },
      ],
      discoveries: [
        {
          title: "表达与事业驱动力",
          description: "事业线与太阳线同时可见时，娱乐角度可理解为表达欲和目标感同框。",
          knowledgeNote: "不代表名气或收入，只是文化象征。",
        },
      ],
    },
  },
  {
    id: "square-palm",
    name: "稳健经营型手型",
    level: "supportive",
    description: "方形掌在娱乐解读中常被归纳为重秩序、耐心和复盘。",
    lines: ["palm-shape"],
    conditions: { required: ["palmShape:square"] },
    source: "palm-knowledge",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.palmShape === "square",
    effects: {
      scores: { personality: 4, wealth: 4 },
      keywords: ["稳健经营"],
      achievements: [
        { name: "稳健经营者", description: "更适合通过秩序、耐心和复盘做长期积累。" },
      ],
    },
  },
  {
    id: "long-palm",
    name: "细腻感知型手型",
    level: "supportive",
    description: "长掌在娱乐解读中常被归纳为对细节、氛围和变化更敏锐。",
    lines: ["palm-shape"],
    conditions: { required: ["palmShape:long"] },
    source: "palm-knowledge",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.palmShape === "long",
    effects: {
      scores: { personality: 5 },
      keywords: ["细腻感知"],
      achievements: [
        { name: "感知型探索者", description: "对细节、氛围和变化可能更敏锐。" },
      ],
    },
  },
  {
    id: "round-palm",
    name: "亲和连接型手型",
    level: "supportive",
    description: "圆掌在娱乐解读中常被归纳为亲和、温和、重互动。",
    lines: ["palm-shape"],
    conditions: { required: ["palmShape:round"] },
    source: "palm-knowledge",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.palmShape === "round",
    effects: {
      scores: { relationship: 4 },
      keywords: ["亲和表达"],
      achievements: [
        { name: "亲和连接者", description: "更容易用温和方式建立互动。" },
      ],
    },
  },
  {
    id: "special-fork",
    name: "多路径思考",
    level: "balanced",
    description: "出现分叉类观察时，转译为多路径思考和选择管理提示。",
    lines: ["special-marks"],
    conditions: { required: ["specialMarks:fork"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.specialMarks.includes("fork"),
    effects: {
      scores: { personality: 3 },
      keywords: ["多路径思考"],
      advice: ["当选择变多时，先写下最重要的一个判断标准。"],
    },
  },
  {
    id: "special-island",
    name: "节奏卡点提醒",
    level: "caution",
    description: "出现岛纹类观察时，只作为节奏卡点提醒，不做负面命运解释。",
    lines: ["special-marks"],
    conditions: { required: ["specialMarks:island"] },
    source: "rule-engine",
    safetyNote: palmistryDisclaimers.short,
    when: (f) => f.specialMarks.includes("island"),
    effects: {
      scores: { energy: -3 },
      advice: ["如果最近感觉卡顿，先减少一个不必要的承诺。"],
    },
  },
  {
    id: "all-unclear",
    name: "照片不适合细读",
    level: "caution",
    description: "三条主线都不稳定时，报告转向通用文化参考和重拍建议。",
    lines: ["life-line", "head-line", "heart-line"],
    conditions: {
      required: ["lifeLine:unclear", "headLine:unclear", "heartLine:unclear"],
      caution: ["photo_visibility"],
    },
    source: "rule-engine",
    safetyNote: "模糊照片不能支撑细节判断。",
    when: (f) =>
      f.lifeLine === "unclear" &&
      f.headLine === "unclear" &&
      f.heartLine === "unclear",
    effects: {
      scores: { personality: -6, career: -4, relationship: -4 },
      discoveries: [
        {
          title: "本次照片不适合细读",
          description: "三条主线都不够稳定，本次报告会以通用文化参考和重拍建议为主。",
          knowledgeNote: "模糊照片不能支撑细节判断。",
        },
      ],
    },
  },
];
